CREATE TABLE IF NOT EXISTS `players` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` TEXT NOT NULL,
  `levels` TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS `admin_tokens` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `token` TEXT NOT NULL,
  `expires_at` INTEGER NOT NULL
);